[credentials]
names = ["Lauro Finance"]
usernames = ["lauro"]
passwords = ["$2b$12$K8CbcfJZJv2gRUuUOSD5DOjCVoZCMTUXIMV0sY7ZfPbVmWZPz3p32"]  # Exemplo de senha criptografada (para "12345")

[cookie]
name = "painel_cookie"
key = "segredo_unico"
expiry_days = 30
